/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alihan (https://sketchfab.com/Dare0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/direction-arrow-6ef46718c7b242e39fcad7f27ee858a5
Title: Direction Arrow
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ArrowModel(props) {
  const { nodes, materials } = useGLTF('/Arrow.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -0.015]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arrow_Material001_0.geometry}
            material={materials['Material.001']}
            position={[11.483, 8.663, 11.398]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Arrow.glb')